name: Update Main README

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Concatenate README files
        run: |
          echo "## Here you can see my Python Projects" > README.md
          echo "" >> README.md
          echo "<details style="border: 1px solid #ccc; padding: 10px; margin-bottom: 10px;"><summary><b>Project 3</b></summary>" >> README.md
          echo "" >> README.md
          cat 3/README.md >> README.md
          echo "" >> README.md
          echo "</details>" >> README.md
          echo "<details><summary><b>Project 4</b></summary>" >> README.md
          echo "" >> README.md
          cat 4/README.md >> README.md
          echo "" >> README.md
          echo "</details>" >> README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m 'Update main README with project details'
          git push
